[project]
name = "smart_charger"
version = "2.0.13"
description = ""
authors = [{ name = "Tobias Terstad", email = "tobias@terstad.se" }]
requires-python = ">=3.13.0"
readme = "README.md"
classifiers = [
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
]
dependencies = [
    "pydantic>=2.12.5,<3",
    "pyyaml>=6.0.3,<7",
    "click>=8.3.1,<9",
    "requests>=2.32.5,<3",
    "paho-mqtt>=2.1.0,<3",
    "mqtt-discovery>=1.0.0,<1.1.0",
    "pyrate-limiter>=4.0.2",
]

[tool.ruff]
lint.extend-select = ["PTH"]

[project.scripts]
mqtt-tool = "smart_charger.tools.mqtt:main"
smart-charger = "smart_charger.smartcharger:main"
ctek-tool = "smart_charger.lib.ctek.ctek_cli:main"

[dependency-groups]
dev = [
    "coverage>=7.13.4",
    "pytest>=9.0.2,<9.1",
    "pytest-cov>=7.0.0",
]

[tool.pytest.ini_options]
markers = [
    "integration: marks tests as integration tests (deselect with '-m \"not integration\"')",
]
addopts = "-m \"not integration\""

[tool.hatch.build.targets.sdist]
include = ["src/smart_charger"]

#[tool.hatch.build.targets.sdist.force-include]
#"settings.yaml" = "settings.yaml"

[tool.hatch.build.targets.wheel]
include = ["src/smart_charger"]

[tool.hatch.build.targets.wheel.sources]
"src/smart_charger" = "smart_charger"

[[tool.uv.index]]
name = "terstad"
url = "http://10.100.0.10:8091/simple"
publish-url = "http://10.100.0.10:8091"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
